inherit_gem:
  relaxed-rubocop: .rubocop.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.4

Layout/LineLength:
  Max: 80

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
