name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [ '2.6', '3.0', 'ruby-head' ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Prepare
        run: |
          git config --global init.defaultBranch main
          git config --global user.email "testuser@example.com"
          git config --global user.name "Test User"
          gem install bundler -v 2.2.8
          bundle install --jobs 4
      - name: Run the specs
        run: |
          bundle exec rspec
      - uses: codecov/codecov-action@v3
        if: matrix.ruby == '3.0'
