name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [ 2.4', '3.0', 'ruby-head' ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Run the specs
        run: |
          gem install bundler -v 2.2.8
          bundle install --jobs 4
          bundle exec rspec
